//
//  BNRStockHolding.h
//  Stocks
//
//  Created by Raffaele Rainone on 17/10/14.
//  Copyright (c) 2014 Raffaele Rainone. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface BNRStockHolding : NSObject

@property (nonatomic) float purchaseSharePrice;//to be redunt one can write @property (nonatomic, readwrite) -- 'readwrite' is the default, the other option is 'readonly' (that does not create a set method). Similarly, we have atomic and nonatomic (the difference between these two regards the multithreading); since atomic is default we need to write nonatomic.
@property (nonatomic) float currentSharePrice;
@property (nonatomic) int numberOfShares;
/*
{
    float _purchaseSharePrice;
    float _currentSharePrice;
    int _numberOfShares;
}

-(float)purchaseSharePrice;
-(void)setPurchaseSharePrice:(float)p;
-(float)currentSharePrice;
-(void)setCurrentSharePrice:(float)c;
-(int)numberOfShares;
-(void)setNumberOfShares:(int)n;
 //All the previous lines can be made automatically generated by the two lines on the top starting with @property
 */
 //the two instance methods
-(float)costInDollars;
-(float)valueIndollars;
//the method to put in the array
-(void)addToArray:(NSMutableArray *)theArray;
@end